name: Get MSI Comments

on:
  push:
    branches:
      - main

jobs:
  get-msi-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
        
    - name: Install Wine and tools for MSI extraction
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine32 wget

    - name: Download the MSI file
      run: |
        wget https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi -O googlechromestandaloneenterprise64.msi

    - name: Extract comments from MSI file
      run: |
        wget https://raw.githubusercontent.com/activescott/lessmsi/master/lessmsi/bin/lessmsi.exe
        wine lessmsi.exe l googlechromestandaloneenterprise64.msi

    - name: Save the output
      run: |
        wine lessmsi.exe x googlechromestandaloneenterprise64.msi output
        cat output/* > msi_comments.txt
      shell: bash
